// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8znNZcv6xBEvZ93btMnbkW
// Component: hfJvyK1l_CkO
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_dashboard.module.css"; // plasmic-import: 8znNZcv6xBEvZ93btMnbkW/projectcss
import sty from "./PlasmicStatistic.module.css"; // plasmic-import: hfJvyK1l_CkO/css

createPlasmicElementProxy;

export const PlasmicStatistic__VariantProps = new Array(
  "hideIcon",
  "hideTrendTracker"
);

export const PlasmicStatistic__ArgProps = new Array(
  "unit",
  "number",
  "timeRange",
  "numberTrend"
);

const $$ = {};

function PlasmicStatistic__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "hideIcon",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.hideIcon
      },
      {
        path: "hideTrendTracker",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          $props.hideTrendTracker
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [sty.roothideIcon]: hasVariant($state, "hideIcon", "hideIcon"),
          [sty.roothideTrendTracker]: hasVariant(
            $state,
            "hideTrendTracker",
            "hideTrendTracker"
          )
        }
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <div className={classNames(projectcss.all, sty.freeBox__miezv)}>
            <p
              className={classNames(
                projectcss.all,
                projectcss.p,
                projectcss.__wab_text,
                sty.p__w0XJu
              )}
            >
              {"Active Users"}
            </p>
            <p.PlasmicImg
              alt={""}
              className={classNames(sty.img__cpNRj, {
                [sty.imghideIcon__cpNRjBa2X9]: hasVariant(
                  $state,
                  "hideIcon",
                  "hideIcon"
                )
              })}
              displayHeight={"auto"}
              displayMaxHeight={"28px"}
              displayMaxWidth={"28px"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              loading={"lazy"}
            />
          </div>
        ),

        value: args.unit,
        className: classNames(sty.slotTargetUnit)
      })}
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox__s3ZB)}
      >
        <div
          className={classNames(projectcss.all, sty.freeBox__cGxPf, {
            [sty.freeBoxhideIcon__cGxPfba2X9]: hasVariant(
              $state,
              "hideIcon",
              "hideIcon"
            )
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents: (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__likJi
                )}
              >
                <React.Fragment>
                  <React.Fragment>{""}</React.Fragment>
                  {
                    <h2
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2__sTa5I
                      )}
                    >
                      {"NULL"}
                    </h2>
                  }

                  <React.Fragment>{""}</React.Fragment>
                </React.Fragment>
              </div>
            ),

            value: args.number
          })}
        </div>
        <div className={classNames(projectcss.all, sty.freeBox___5WK)}>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__sZm6I, {
              [sty.freeBoxhideTrendTracker__sZm6Iy1F5D]: hasVariant(
                $state,
                "hideTrendTracker",
                "hideTrendTracker"
              )
            })}
          >
            <div
              className={classNames(projectcss.all, sty.freeBox__tV10B, {
                [sty.freeBoxhideTrendTracker__tV10By1F5D]: hasVariant(
                  $state,
                  "hideTrendTracker",
                  "hideTrendTracker"
                )
              })}
            >
              <div className={classNames(projectcss.all, sty.freeBox___6YLg)}>
                {p.renderPlasmicSlot({
                  defaultContents: "NULL",
                  value: args.numberTrend,
                  className: classNames(sty.slotTargetNumberTrend)
                })}
              </div>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__eynvx)}>
              <div className={classNames(projectcss.all, sty.freeBox__wg7Pb)}>
                {p.renderPlasmicSlot({
                  defaultContents: "from last month",
                  value: args.timeRange,
                  className: classNames(sty.slotTargetTimeRange)
                })}
              </div>
            </div>
          </p.Stack>
        </div>
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStatistic__ArgProps,
          internalVariantPropNames: PlasmicStatistic__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStatistic__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStatistic";
  } else {
    func.displayName = `PlasmicStatistic.${nodeName}`;
  }
  return func;
}

export const PlasmicStatistic = Object.assign(
  // Top-level PlasmicStatistic renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicStatistic
    internalVariantProps: PlasmicStatistic__VariantProps,
    internalArgProps: PlasmicStatistic__ArgProps
  }
);

export default PlasmicStatistic;
/* prettier-ignore-end */
