// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8znNZcv6xBEvZ93btMnbkW
// Component: 0dtRZs-Cak-j
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import PageLayout from "../../PageLayout"; // plasmic-import: zTrlxyMj1N6v/component
import { AntdDatePicker } from "@plasmicpkgs/antd5/skinny/registerDatePicker";
import { datePickerHelpers as AntdDatePicker_Helpers } from "@plasmicpkgs/antd5/skinny/registerDatePicker";
import Statistic from "../../Statistic"; // plasmic-import: hfJvyK1l_CkO/component
import { AntdSelect } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { SimpleChart } from "@plasmicpkgs/react-chartjs-2";
import { useScreenVariants as useScreenVariantssmtTcemE2Fpl } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: SmtTcemE2FPL/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic_plasmic_rich_components.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic_dashboard.module.css"; // plasmic-import: 8znNZcv6xBEvZ93btMnbkW/projectcss
import sty from "./PlasmicBusinessMetrics.module.css"; // plasmic-import: 0dtRZs-Cak-j/css
import image74Uhp4Lv2P9Eu from "./images/image7.svg"; // plasmic-import: 4Uhp4Lv2p9EU/picture
import orderIconHYkVxeanKSa3 from "./images/orderIcon.svg"; // plasmic-import: hYKVxeanKSa3/picture
import dollarIconRcOk0XfMjO from "./images/dollarIcon.svg"; // plasmic-import: Rc_ok0xfMj_o/picture

createPlasmicElementProxy;

export const PlasmicBusinessMetrics__VariantProps = new Array();

export const PlasmicBusinessMetrics__ArgProps = new Array();

const $$ = {};

function PlasmicBusinessMetrics__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  let [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "start.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: p.generateOnMutateForSpec("value", AntdDatePicker_Helpers)
      },
      {
        path: "end.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``,
        onMutate: p.generateOnMutateForSpec("value", AntdDatePicker_Helpers)
      },
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "month"
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = p.useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const new$Queries = {
    topRevByCountryInDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "nuKzkKRXx5eZpXXNjRbQir",
        opId: "bfe825fe-d55f-45e9-90c4-cfd6f4530839",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.bfe825fe-d55f-45e9-90c4-cfd6f4530839.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    ordersByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "nuKzkKRXx5eZpXXNjRbQir",
        opId: "aebb2ce1-a0ca-4baf-8a28-93dc31f0e100",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.aebb2ce1-a0ca-4baf-8a28-93dc31f0e100.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    signupsByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "nuKzkKRXx5eZpXXNjRbQir",
        opId: "2f10bb8e-c823-467d-a754-83b7f4a9f58b",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.2f10bb8e-c823-467d-a754-83b7f4a9f58b.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    totalRevByCustomDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "nuKzkKRXx5eZpXXNjRbQir",
        opId: "71946c6d-6d54-44d0-a549-5c6b0ac32e9c",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.71946c6d-6d54-44d0-a549-5c6b0ac32e9c.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    monthlyRevByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "nuKzkKRXx5eZpXXNjRbQir",
        opId: "45432e2c-850f-40c8-95c6-2278f0658c1c",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.45432e2c-850f-40c8-95c6-2278f0658c1c.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    quarterlyRevByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "nuKzkKRXx5eZpXXNjRbQir",
        opId: "0356fe1f-31f4-4a5a-85d1-378f28c716cd",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.0356fe1f-31f4-4a5a-85d1-378f28c716cd.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantssmtTcemE2Fpl()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
          >
            <ph.DataCtxReader>
              {$ctx => (
                <React.Fragment>
                  <section
                    className={classNames(projectcss.all, sty.section__ygtOb)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__aHk0U)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"Business Metrics"}
                      </h1>
                    </div>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section___1MUy)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___8Z11X
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__aNRxX
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__wAkGy
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {"Custom date range analysis"}
                            </span>
                          </React.Fragment>
                        </h2>
                      </div>
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__tpmoY
                        )}
                      >
                        {(() => {
                          const child$Props = {
                            allowClear: true,
                            bordered: true,
                            className: classNames("__wab_instance", sty.start),
                            onChange:
                              p.generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["start", "value"],
                                AntdDatePicker_Helpers
                              ),
                            picker: "date",
                            popupBodyClassName: classNames({
                              [sty["pcls_rVhKrxnm1zNx"]]: true
                            }),
                            popupClassName: classNames({
                              [sty["pcls_rP6FpVvd-WUu"]]: true
                            }),
                            popupHeaderClassName: classNames({
                              [sty["pcls_8SxzZGXeFBqA"]]: true
                            }),
                            popupScopeClassName: sty["start__datePickerPopup"],
                            showTime: false,
                            value: p.generateStateValueProp($state, [
                              "start",
                              "value"
                            ])
                          };
                          p.initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "start.value"
                              }
                            ],

                            [],
                            AntdDatePicker_Helpers ?? {},
                            child$Props
                          );
                          return (
                            <AntdDatePicker
                              data-plasmic-name={"start"}
                              data-plasmic-override={overrides.start}
                              {...child$Props}
                            />
                          );
                        })()}
                        {(() => {
                          const child$Props = {
                            allowClear: true,
                            bordered: true,
                            className: classNames("__wab_instance", sty.end),
                            defaultValue: ``,
                            onChange:
                              p.generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["end", "value"],
                                AntdDatePicker_Helpers
                              ),
                            picker: "date",
                            popupScopeClassName: sty["end__datePickerPopup"],
                            value: p.generateStateValueProp($state, [
                              "end",
                              "value"
                            ])
                          };
                          p.initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "end.value"
                              }
                            ],

                            [],
                            AntdDatePicker_Helpers ?? {},
                            child$Props
                          );
                          return (
                            <AntdDatePicker
                              data-plasmic-name={"end"}
                              data-plasmic-override={overrides.end}
                              {...child$Props}
                            />
                          );
                        })()}
                      </p.Stack>
                    </div>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__erzH5)}
                    >
                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic___1T9VO
                        )}
                        hideTrendTracker={true}
                        number={
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__xKiR2
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $queries.signupsByDateRange.data[0]
                                    .signup_count;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "NULL";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </h2>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__v52Q6
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jsgh3
                              )}
                              style={(() => {
                                try {
                                  return undefined;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return undefined;
                                  }
                                  throw e;
                                }
                              })()}
                            >
                              {"Sign-ups"}
                            </div>
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__cGTtf)}
                              displayHeight={"auto"}
                              displayMaxHeight={"24px"}
                              displayMaxWidth={"24px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: image74Uhp4Lv2P9Eu,
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />

                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic__acnO
                        )}
                        hideTrendTracker={true}
                        number={
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__eGxgJ
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $queries.ordersByDateRange.data[0]
                                    .order_count;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "NULL";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </h2>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___4Rdsn
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__wocUt
                              )}
                            >
                              {"Orders"}
                            </div>
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__sl3Yg)}
                              displayHeight={"auto"}
                              displayMaxHeight={"24px"}
                              displayMaxWidth={"24px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: orderIconHYkVxeanKSa3,
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />

                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic__ropZd
                        )}
                        hideTrendTracker={true}
                        number={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___2EsoJ
                            )}
                          >
                            <h2
                              className={classNames(
                                projectcss.all,
                                projectcss.h2,
                                projectcss.__wab_text,
                                sty.h2__pcDJf
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return (
                                      "$" +
                                      Intl.NumberFormat("en").format(
                                        $queries.totalRevByCustomDateRange
                                          .data[0].total_revenue
                                      )
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "NULL";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </h2>
                          </div>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__uu8Qa
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__jyaZw
                              )}
                            >
                              {"Revenue"}
                            </div>
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__nxHmT)}
                              displayHeight={"auto"}
                              displayMaxHeight={"24px"}
                              displayMaxWidth={"24px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: dollarIconRcOk0XfMjO,
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />
                    </p.Stack>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section___0YKaw)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__bMwPw)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___9OcXd
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__ze5To
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {"Revenue Trends"}
                            </span>
                          </React.Fragment>
                        </h2>
                        <AntdSelect
                          data-plasmic-name={"select"}
                          data-plasmic-override={overrides.select}
                          bordered={true}
                          className={classNames("__wab_instance", sty.select)}
                          defaultOpen={false}
                          defaultStylesClassName={classNames(
                            projectcss.root_reset,
                            projectcss.plasmic_default_styles,
                            projectcss.plasmic_mixins,
                            projectcss.plasmic_tokens,
                            plasmic_antd_5_hostless_css.plasmic_tokens,
                            plasmic_plasmic_rich_components_css.plasmic_tokens
                          )}
                          defaultValue={"month"}
                          onChange={p.generateStateOnChangeProp($state, [
                            "select",
                            "value"
                          ])}
                          options={(() => {
                            const __composite = [
                              { value: null, label: null, type: null },
                              { value: null, label: null, type: "option" }
                            ];

                            __composite["0"]["value"] = "month";
                            __composite["0"]["label"] = "month";
                            __composite["0"]["type"] = "option";
                            __composite["1"]["value"] = "quarterly";
                            __composite["1"]["label"] = "quarterly";
                            return __composite;
                          })()}
                          placeholder={"Select..."}
                          popupScopeClassName={sty["select__popup"]}
                          value={p.generateStateValueProp($state, [
                            "select",
                            "value"
                          ])}
                        />
                      </div>
                      <SimpleChart
                        className={classNames(
                          "__wab_instance",
                          sty.chart__xiPzL
                        )}
                        data={
                          $state.select.value === "month"
                            ? $queries.monthlyRevByDateRange.data
                            : $queries.quarterlyRevByDateRange.data
                        }
                        interactive={false}
                        title={``}
                        type={"bar"}
                      />
                    </p.Stack>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__yfDpR)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__vwL8V)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__w0Pqh
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__es9XR
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {"Revenue per country: within the last year"}
                            </span>
                          </React.Fragment>
                        </h2>
                      </div>
                      <SimpleChart
                        className={classNames(
                          "__wab_instance",
                          sty.chart__dhplg
                        )}
                        data={$queries.topRevByCountryInDateRange.data}
                        interactive={false}
                        labelField={"country"}
                        title={"Revenue by country"}
                        type={"bar"}
                      />
                    </p.Stack>
                  </section>
                </React.Fragment>
              )}
            </ph.DataCtxReader>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "pageLayout", "h1", "start", "end", "select"],
  pageLayout: ["pageLayout", "h1", "start", "end", "select"],
  h1: ["h1"],
  start: ["start"],
  end: ["end"],
  select: ["select"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBusinessMetrics__ArgProps,
          internalVariantPropNames: PlasmicBusinessMetrics__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBusinessMetrics__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBusinessMetrics";
  } else {
    func.displayName = `PlasmicBusinessMetrics.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard(WrappedComponent) {
  const PageGuard = props => (
    <p.PlasmicPageGuard
      minRole={null}
      appId={"8znNZcv6xBEvZ93btMnbkW"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <WrappedComponent {...props} />
    </p.PlasmicPageGuard>
  );

  return PageGuard;
}

function withUsePlasmicAuth(WrappedComponent) {
  const WithUsePlasmicAuthComponent = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "8znNZcv6xBEvZ93btMnbkW"
    });
    return (
      <p.PlasmicDataSourceContextProvider
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </p.PlasmicDataSourceContextProvider>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicBusinessMetrics = Object.assign(
  // Top-level PlasmicBusinessMetrics renders the root element
  withUsePlasmicAuth(withPlasmicPageGuard(makeNodeComponent("root"))),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    h1: makeNodeComponent("h1"),
    start: makeNodeComponent("start"),
    end: makeNodeComponent("end"),
    select: makeNodeComponent("select"),
    // Metadata about props expected for PlasmicBusinessMetrics
    internalVariantProps: PlasmicBusinessMetrics__VariantProps,
    internalArgProps: PlasmicBusinessMetrics__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBusinessMetrics;
/* prettier-ignore-end */
